services:
  traefik:
    image: traefik:v2.0.2
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/storage:/storage
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.justAdummyService.loadbalancer.server.port=1337"
      - "traefik.http.routers.traefikRouter.rule=Host(`127.0.0.11`)"
      - "traefik.http.routers.traefikRouter.service=api@internal"
      - "traefik.http.routers.traefikRouter.entrypoints=traefik"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=https_redir@docker"
      - "traefik.http.middlewares.https_redir.redirectscheme.scheme=https"
      - "traefik.docker.network=test_db_default" 
  rodica_prod:
    image: wordpress:6.6.2-apache
    container_name: wordpress
    depends_on:
      - backend
      - wordpress_db
    labels:
      - "traefik.http.routers.rodica.entrypoints=https"
      - "traefik.http.routers.rodica.middlewares=https_redir"
      - "traefik.http.routers.rodica.rule=Host(`www.rodica.ro, rodica.ro`)"
      - "traefik.http.routers.rodica.service=rodica"
      - "traefik.http.routers.rodica.tls.certresolver=le"
      - "traefik.http.services.rodica.loadbalancer.server.port=80"
    volumes:
      - ./rodica/:/var/www/html
  rodica_wordpress_db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./wordpress_db/data:/var/lib/mysql
            

